### ISSUE TITLE
Observed a panic: "slice bounds out of range" (runtime error: slice bounds out of range)

### ISSUE THREAD

**Issue by choseh** [Appdynamics/cluster-agent#3]
Hi,

we're experiencing a crash.

`E0521 10:47:52.327633       1 runtime.go:73] Observed a panic: "slice bounds out of range" (runtime error: slice bounds out of range)
goroutine 150 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1216180, 0x20d0290)
	/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x82
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x1216180, 0x20d0290)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/appdynamics/cluster-agent/workers.(*DeployWorker).processObject(0xc000118bd0, 0xc0011d7780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/github.com/appdynamics/cluster-agent/workers/deploy.go:322 +0x7dc
github.com/appdynamics/cluster-agent/workers.(*DeployWorker).onNewDeployment(0xc000118bd0, 0x134f320, 0xc0011d7780)
	/usr/local/go/src/github.com/appdynamics/cluster-agent/workers/deploy.go:104 +0x175
github.com/appdynamics/cluster-agent/workers.(*DeployWorker).onNewDeployment-fm(0x134f320, 0xc0011d7780)
	/usr/local/go/src/github.com/appdynamics/cluster-agent/workers/deploy.go:67 +0x3e
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc0000183f0, 0xc000018410, 0xc000018400, 0x134f320, 0xc0011d7780)
	/go/src/k8s.io/client-go/tools/cache/controller.go:195 +0x49
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x2, 0xc0000fcf00, 0xc000357400)
	/go/src/k8s.io/client-go/tools/cache/shared_informer.go:607 +0x21d
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00062fe18, 0x42d752, 0xc000357430)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:284 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/src/k8s.io/client-go/tools/cache/shared_informer.go:601 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00036b768)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00062ff68, 0xdf8475800, 0x0, 0x11f7701, 0xc0003d2d20)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xbe
k8s.io/apimachinery/pkg/util/wait.Until(0xc00036b768, 0xdf8475800, 0xc0003d2d20)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0003d4280)
	/go/src/k8s.io/client-go/tools/cache/shared_informer.go:599 +0x8d
k8s.io/client-go/tools/cache.(*processorListener).run-fm()
	/go/src/k8s.io/client-go/tools/cache/shared_informer.go:443 +0x2a
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000118d80, 0xc0001f1af0)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range
`

any way to debug which deployment/resource causes this to happen?

Alex

**Comment by sashaPM** [comment]
long annotations for deployments were not properly truncated. The issue should be resolved in 0.1.7

**Comment by choseh** [comment]
```
func TruncateString(str string, maxLength int) string {
￼        result := str
￼        if len(str) > maxLength {
￼            diff := len(str) - maxLength
￼            result = str[0:diff]
￼        }
￼        return result
￼    }
```

I'm not very good with math, but wouldn't this result in a return of a 2000 character string, when throwing in a 6000 character string (for example)?

```
func TruncateString(6000, 4000) string {
￼        result := 6000
￼        if len(6000) > 4000 {
￼            diff := 6000 - 4000
￼            result = str[0:2000]
￼        }
￼        return 2000
￼    }
```

**Comment by sashaPM** [comment]
@choseh Your math is perfect. It was released this way to get you going while the underlying limit was investigated.
The issue should be fully resolved with the recently released 0.1.8
